### ISSUE TITLE
yo trails crashing when trailpack doesn't have v2-latest tag

### ISSUE THREAD

**Issue by Nishchit14** [trailsjs/trails#276]
#### Issue Description
`yo trails` not generating default folders `controllers` & `models` in api folder. 
Due to this `config/web.js` also not generating itself.

Some **trailpacks**'s not been installed, Error is as below

```
npm ERR! Linux 4.8.0-32-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "trailpack-express@v2-latest" "trailpack-mongoose@v2-latest" "trailpack-footprints@v2-latest" "express@5.0.0-alpha.2" "--save" "--silent" "--loglevel=error"
npm ERR! node v6.0.9
npm ERR! npm  v4.1.1
npm ERR! code ETARGET
npm ERR! notarget No compatible version found: trailpack-mongoose@v2-latest
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.1.0, 0.2.0, 0.2.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 1.0.0, 1.0.1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/nd/Desktop/ND/trails-hello/npm-debug.log
1
┌───────────────────────────────────────────┐
│ Your Trails Application has been created! │
│ ---                                       │
│ To start your application, run: npm start │
```
#### Environment
- node version: 6.0
- trails version: 2
- operating system: Ubuntu16.10 & Mac Sierra

**Comment by jaumard** [comment]
It's not because of express 5 at all, it's just because trailpack-mongoose doesn't have a v2 version. But there an open PR about it here https://github.com/trailsjs/trailpack-mongoose/pull/26

**Comment by konstantinzolotarev** [comment]
@Nishchit14 @jaumard Will be done in 10 mins

**Comment by konstantinzolotarev** [comment]
@Nishchit14 Could you please update version in your `package.json` to `2.0.0` and reinstall dependencies. new version released 
https://www.npmjs.com/package/trailpack-mongoose

**Comment by Nishchit14** [comment]
@jaumard @konstantinzolotarev 
Same error exists in new `yo trails` setup.

**Comment by jaumard** [comment]
@konstantinzolotarev @Nishchit14 yeah the generator install the tag v2-latest witch doesn't exist for this trailpack. @tjwebb why did you use v2-latest instead of 2^ ? Because it force to have this v2-latest tag witch will not work with third party trailpack (that you can install with the generator btw) or force dev to create this tag too

**Comment by konstantinzolotarev** [comment]
Pushed a new tag

**Comment by tjwebb** [comment]
what's the status of this? the `v2-latest` stuff was because of the crazy dependency graph that I needed to resolve in order to release v2. I've mitigated a lot of this for v3

**Comment by Nishchit14** [comment]
@trailsjs/maintainers 
Nudge Nudge !!

**Comment by shinobiwarrior** [comment]
Hi, sorry I'm commenting on a closed issue, but I'm getting this error on a fresh install (literally installed the generator 10 minutes ago). I can modify the package.json manually, but it doesn't feel right... So, is there going to be a fix for this?

**Comment by tjwebb** [comment]
Which orm/webserver are you selecting during install?

**Comment by shinobiwarrior** [comment]
I'm choosing express and mongoose.

**Comment by jaumard** [comment]
It's fix but trails need to be deployed in order to deploy the fix

**Comment by shinobiwarrior** [comment]
Ok, any ETA? I'm not trying to hurry you, just want to organize myself

**Comment by tjwebb** [comment]
Soon :) The latest version of Trails is building right now: https://travis-ci.org/trailsjs/trails/builds/210139986

@jaumard the fix is contained therein?

**Comment by shinobiwarrior** [comment]
Ok, I see it passed the test, but I'm not getting it yet... Do you know how much time does it take to be reflected? (sorry to bother you, it's the first time I really need an update like this, so I've never even thought about this procedures)

**Comment by shinobiwarrior** [comment]
If I do `npm info generator-trails versions`, the last version I get is 2.0.1, any clue of why is this happening?

**Comment by hdon** [comment]
I've made a gist affected by a similar issue with version 2.0.1. The thread seems to suggest the issue is fixed in version 2.0.2 so perhaps I'll just have to wait until new npm release?

The npm errors begin on line 254:

https://gist.github.com/hdon/4d92d32127df8c10927572f1043297df#file-gistfile1-txt-L254

**Comment by shinobiwarrior** [comment]
Hi @tjwebb , could you please update the generator too? It's still on 2.0.1... Thanks!

**Comment by toledosteve** [comment]
Any progress on this issue?  It seems like a fix is in the works, but a fresh install of Trails based off the very easy install instructions on the website breaks.

**Comment by tjwebb** [comment]
@toledosteve are you choosing the default webserver/orm options, or other ones? I can't reproduce at the moment...

**Comment by matthewdarwin** [comment]
It is failing for me when choosing bookshelf.  (trailpack-bookshelf@v2-latest)

**Comment by jaumard** [comment]
Normally it's fixed but Trails and/or the generator need to be redeployed on npm to fix this

**Comment by danielzen** [comment]
Is there a workaround to the @v2-latest issue so as to use generator-trails with trailpack-mongoose in the meantime?

**Comment by jaumard** [comment]
You can try to use `generator-trails` master branch and see if it's works, but if not it means that a new version of Trails need to be deploy and there no workaround except choose none as ORM and install trailpack-mongoose manually witch it's basically only a `npm install`, add the trailpack under `main.js` and then copy `database.js` file into your project.

**Comment by jaumard** [comment]
Should be fixed with generator-trails@2.0.3 if not don't hesitate to reopen this

**Comment by anakinjay** [comment]
Seeing this issue still, fresh install 10 minutes ago:

npm ERR! No compatible version found: trailpack-mongoose@v2-latest
npm ERR! Valid install targets:
npm ERR! 2.1.1, 2.1.0, 2.0.0, 1.0.1, 1.0.0, 0.4.4, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.0, 0.2.2, 0.2.0, 0.1.0
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

**Comment by analogrithems** [comment]
Still getting this with bookshelf

`npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/analog/.nvm/versions/node/v7.8.0/bin/node" "/Users/analog/.nvm/versions/node/v7.8.0/bin/npm" "install" "trailpack-hapi@v2-latest" "trailpack-bookshelf@v2-latest" "trailpack-footprints@v2-latest" "--save" "--silent" "--loglevel=error"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: trailpack-bookshelf@v2-latest
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0-alpha-1
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/analog/.npm/_logs/2017-09-11T06_37_28_547Z-debug.log
1
┌───────────────────────────────────────────┐
│ Your Trails Application has been created! │
│ ---                                       │
│ To start your application, run: npm start │
└───────────────────────────────────────────┘
`

**Comment by konstantinzolotarev** [comment]
@analogrithems I think it would be better to place same issue into `trailpack-bookshelf` repo.

**Comment by dericcain** [comment]
I am also running into this issue. Here are the steps to reproduce:
```
npm install -g yo generator-trails
yo trails
// choose express
// choose mongoose
// choose footprints
```
I get this error:
```
15 verbose type tag
16 verbose stack trailpack-mongoose: No matching version found for trailpack-mongoose@v2-latest
16 verbose stack     at pickManifest (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/npm-pick-manifest/index.js:61:11)
16 verbose stack     at fetchPackument.then.packument (/usr/local/lib/node_modules/npm/node_modules/pacote/lib/fetchers/registry/manifest.js:51:18)
16 verbose stack     at tryCatcher (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
16 verbose stack     at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:512:31)
16 verbose stack     at Promise._settlePromise (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:569:18)
16 verbose stack     at Promise._settlePromise0 (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
16 verbose stack     at Promise._settlePromises (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
16 verbose stack     at Async._drainQueue (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:133:16)
16 verbose stack     at Async._drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:143:10)
16 verbose stack     at Immediate.Async.drainQueues (/usr/local/lib/node_modules/npm/node_modules/bluebird/js/release/async.js:17:14)
16 verbose stack     at runCallback (timers.js:781:20)
16 verbose stack     at tryOnImmediate (timers.js:743:5)
16 verbose stack     at processImmediate [as _immediateCallback] (timers.js:714:5)
17 verbose cwd /Users/webdev2/Sites/node/trails
18 verbose Darwin 16.7.0
19 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "trailpack-hapi@v2-latest" "trailpack-mongoose@v2-latest" "trailpack-footprints@v2-latest" "--save" "--silent" "--loglevel=error"
20 verbose node v8.5.0
21 verbose npm  v5.4.2
22 error code ETARGET
23 error notarget No matching version found for trailpack-mongoose@v2-latest
24 error notarget In most cases you or one of your dependencies are requesting
24 error notarget a package version that doesn't exist.
25 verbose exit [ 1, true ]
```

**Comment by Nishchit14** [comment]
@tjwebb @jaumard any updates in this issue?
